[package]
name = "btf-tracepoint-example-common"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = [ "aya" ]

[dependencies]
aya = { git = "https://github.com/joshuataylor/aya", branch = "feature/enum64", optional=true }

[lib]
path = "src/lib.rs"
